### ISSUE TITLE
Link in advanced/chapter_01.yml not working anymore

### ISSUE THREAD

**Issue by jamesv1994** [sivel/ansible-training-content#2]
Hi,
the link in advanced/chapter_01.yml (http://bit.ly/ansible_advanced) is not working anymore!
It is refering to a page:
Expired
The account you are trying to access has expired.

Don´t know if this is recent, but I wanted take a look at the advanced training.

**Comment by sivel** [comment]
This repo, although the original source, is no longer maintained.

This repo was forked to https://github.com/ansible/training-content  however ansible has decided to no longer use this material and move to official Red Hat training material.  

You can find more information about the training material in:

https://www.ansible.com/training-certification
